### ISSUE TITLE
Can you guide me how to ues it?

### ISSUE THREAD

**Issue by ChrisWen960216** [momocow/node-cq-websocket#28]
I download the cpk for CoolQ HTTP and install the package for node-cq-websocket,how can I start?

**Comment by momocow** [comment]
I'll provide some simple steps to demo the usage.

To learn more, it is recommended to read the **document** of both[ `node-cq-websocket`](https://github.com/momocow/node-cq-websocket/blob/master/README.md) and [CQHTTP API](https://cqhttp.cc/docs/4.4/#). Besides, you can join [the QQ group of CQHTTP API](https://github.com/richardchien/coolq-http-api#%E9%97%AE%E9%A2%98bug-%E5%8F%8D%E9%A6%88%E6%84%8F%E8%A7%81%E5%92%8C%E5%BB%BA%E8%AE%AE) to ask for helps.

--- 

1. Deploy your CoolQ instance with CQHTTP API plugin configured. (Read more to learn [how to configure CQHTTP API](https://cqhttp.cc/docs/4.4/#/Configuration)). Make sure you have WebSocket enabled when configuring CQHTTP API.
```ini
# config.ini
use_ws = true

# for convenience, you can leave the rest of configs by default
```

2. In your nodejs project, create a CQWebSocket instance with default configs (or read [this](https://github.com/momocow/node-cq-websocket#new-cqwebsocketopt) to customize your config).
```js
const CQWebSocket = require('cq-websocket')

// default configs
let bot = new CQWebSocket()

// listen on all types of messages and print them to the console
bot.on('message', (e, context) => {
    console.log(context.raw_message)
})
```

3. Launch your nodejs bot on the same host as CoolQ instance (because the default host of CQWebSocket is `127.0.0.1`) and say something to the bot.

---

**Caveat**
- Ensure `use_ws` is enabled (`yes`, `true` or `1`) in the config file of CQHTTP API.
- If you want to customize your host and port, make sure that the host and port provided to CQWebSocket constructor always matches with those configured in the config file of CQHTTP API, which are `ws_host` and `ws_port`.

**Comment by ChrisWen960216** [comment]
Thanks for your guide,I will try.

**Comment by momocow** [comment]
I'll close this issue since it has been idle for a week.
Feel free to reopen it if you need further support.
